### ISSUE TITLE
Exception when running with es 5.2

### ISSUE THREAD

**Issue by pumpadump** [andrewvc/wikiparse#8]
When i try to run the jar it throws the following exception, what could be the problem?:

`Deleting index en-wikipedia
Creating index en-wikipedia
Exception in thread "main" clojure.lang.ExceptionInfo: clj-http: status 400 {:object {:orig-content-encoding "gzip", :trace-redirects ["http://localhost:9200/en-wikipedia"], :request-time 42, :status 400, :headers {"transfer-encoding" "chunked", "content-type" "text/plain; charset=UTF-8"}, :body "No handler found for uri [/en-wikipedia] and method [POST]"}, :environment {client #<client$wrap_output_coercion$fn__3762 clj_http.client$wrap_output_coercion$fn__3762@867ba60>, req {:headers {"accept" "application/json"}, :request-method :post, :url "http://localhost:9200/en-wikipedia", :body "{\"settings\":{\"index\":{\"number_of_replicas\":0,\"gateway\":{\"local\":{\"sync\":\"60s\"}},\"translog\":{\"flush_threshold_size\":\"756mb\",\"interval\":\"60s\"},\"number_of_shards\":1,\"refresh_interval\":60}},\"mappings\":{\"page\":{\"properties\":{\"redirects\":{\"fields\":{\"redirects_snow\":{\"type\":\"string\",\"analyzer\":\"snowball\"},\"redirects_simple\":{\"type\":\"string\",\"analyzer\":\"simple\"},\"redirects_exact\":{\"index\":\"not_analyzed\",\"type\":\"string\"}},\"type\":\"string\"},\"format\":{\"index\":\"not_analyzed\",\"type\":\"string\"},\"ns\":{\"index\":\"not_analyzed\",\"type\":\"string\"},\"title\":{\"fields\":{\"title_snow\":{\"type\":\"string\",\"analyzer\":\"snowball\"},\"title_exact\":{\"index\":\"not_analyzed\",\"type\":\"string\"},\"title_simple\":{\"type\":\"string\",\"analyzer\":\"simple\"}},\"type\":\"string\"},\"suggest\":{\"index_analyzer\":\"simple\",\"type\":\"completion\",\"search_analyzer\":\"simple\"},\"redirect\":{\"index\":\"not_analyzed\",\"type\":\"string\"},\"timestamp\":{\"type\":\"date\"},\"body\":{\"fields\":{\"body_snow\":{\"type\":\"string\",\"analyzer\":\"snowball\"},\"body_simple\":{\"type\":\"string\",\"analyzer\":\"simple\"}},\"type\":\"string\"}},\"_all\":{\"_enabled\":false}}}}"}, map__3646 {:orig-content-encoding "gzip", :trace-redirects ["http://localhost:9200/en-wikipedia"], :request-time 42, :status 400, :headers {"transfer-encoding" "chunked", "content-type" "text/plain; charset=UTF-8"}, :body "No handler found for uri [/en-wikipedia] and method [POST]"}, resp {:orig-content-encoding "gzip", :trace-redirects ["http://localhost:9200/en-wikipedia"], :request-time 42, :status 400, :headers {"transfer-encoding" "chunked", "content-type" "text/plain; charset=UTF-8"}, :body "No handler found for uri [/en-wikipedia] and method [POST]"}, status 400}}
	at clj_http.client$wrap_exceptions$fn__3645.invoke(client.clj:171)
	at clj_http.client$wrap_accept$fn__3802.invoke(client.clj:521)
	at clj_http.client$wrap_accept_encoding$fn__3808.invoke(client.clj:536)
	at clj_http.client$wrap_content_type$fn__3797.invoke(client.clj:512)
	at clj_http.client$wrap_form_params$fn__3878.invoke(client.clj:683)
	at clj_http.client$wrap_nested_params$fn__3895.invoke(client.clj:707)
	at clj_http.client$wrap_method$fn__3848.invoke(client.clj:624)
	at clj_http.cookies$wrap_cookies$fn__704.invoke(cookies.clj:122)
	at clj_http.links$wrap_links$fn__2197.invoke(links.clj:50)
	at clj_http.client$wrap_unknown_host$fn__3903.invoke(client.clj:726)
	at clj_http.client$post.doInvoke(client.clj:841)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojurewerkz.elastisch.rest$post.invoke(rest.clj:48)
	at clojurewerkz.elastisch.rest.index$create.doInvoke(index.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at wikiparse.core$ensure_index.invoke(core.clj:190)
	at wikiparse.core$_main.doInvoke(core.clj:268)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at wikiparse.core.main(Unknown Source)`

**Comment by leoamigood** [comment]
Having same issue with ES 5.4
